In [ ]:
#passo 1:  Importar a base de dados
#passo 2: visualizar a base de dados
# - intender as informações que está disponível
# - descobrir as erros da base de dados

#passo 3: Tratamento de dados
#passo 4: análise inicial
#passo 5: analise detalhada - descobrir as causas do cancelamento

In [ ]:
# INSTRUÇÕES
# axis = 0 -> linha ; axis = 1 -> coluna

In [9]:
import pandas as pd

#passo 1:  Importar a base de dados
tabela = pd.read_csv(r"arquivos\telecom_users.csv")
#passo 2: visualizar a base de dados
#display(tabela)
# - intender as informações que está disponível
# - descobrir as erros da base de dados e tratar 
tabela = tabela.drop("Unnamed: 0", axis=1) # excluir coluna
tabela["TotalGasto"]=pd.to_numeric(tabela["TotalGasto"], errors="coerce") # transforma os dados da coluna em floate, em errors podecolocar o ignore->ingorar os erros, raise-> mostrar erro, coerce -> forcar a barra
tabela = tabela.dropna(how='all', axis=1) # excluir counas que esteja totalmete vazias, how = 'all' -> colunas vazias
tabela = tabela.dropna(how='any', axis=0) # excluir linhas que tiver algum campo vazio, how='any' -> algum campo vazio
display(tabela)

,IDCliente,Genero,Aposentado,Casado,Dependentes,MesesComoCliente,ServicoTelefone,MultiplasLinhas,ServicoInternet,ServicoSegurancaOnline,...,ProtecaoEquipamento,ServicoSuporteTecnico,ServicoStreamingTV,ServicoFilmes,TipoContrato,FaturaDigital,FormaPagamento,ValorMensal,TotalGasto,Churn
0,7010-BRBUU,Masculino,0,Sim,Sim,72,Sim,Sim,Nao,SemInternet,...,SemInternet,SemInternet,SemInternet,SemInternet,2 anos,Nao,CartaoCredito,24.10,1734.65,Nao
1,9688-YGXVR,Feminino,0,Nao,Nao,44,Sim,Nao,Fibra,Nao,...,Sim,Nao,Sim,Nao,Mensal,Sim,CartaoCredito,88.15,3973.20,Nao
2,9286-DOJGF,Feminino,1,Sim,Nao,38,Sim,Sim,Fibra,Nao,...,Nao,Nao,Nao,Nao,Mensal,Sim,DebitoAutomatico,74.95,2869.85,Sim
3,6994-KERXL,Masculino,0,Nao,Nao,4,Sim,Nao,DSL,Nao,...,Nao,Nao,Nao,Sim,Mensal,Sim,BoletoEletronico,55.90,238.50,Nao
4,2181-UAESM,Masculino,0,Nao,Nao,2,Sim,Nao,DSL,Sim,...,Sim,Nao,Nao,Nao,Mensal,Nao,BoletoEletronico,53.45,119.50,Nao
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5981,0684-AOSIH,Masculino,0,Sim,Nao,1,Sim,Nao,Fibra,Sim,...,Nao,Nao,Sim,Sim,Mensal,Sim,BoletoEletronico,95.00,95.00,Sim
5982,5982-PSMKW,Feminino,0,Sim,Sim,23,Sim,Sim,DSL,Sim,...,Sim,Sim,Sim,Sim,2 anos,Sim,CartaoCredito,91.10,2198.30,Nao
5983,8044-BGWPI,Masculino,0,Sim,Sim,12,Sim,Nao,Nao,SemInternet,...,SemInternet,SemInternet,SemInternet,SemInternet,Mensal,Sim,BoletoEletronico,21.15,306.05,Nao
5984,7450-NWRTR,Masculino,1,Nao,Nao,12,Sim,Sim,Fibra,Nao,...,Sim,Nao,Sim,Sim,Mensal,Sim,BoletoEletronico,99.45,1200.15,Sim
5985,4795-UXVCJ,Masculino,0,Nao,Nao,26,Sim,Nao,Nao,SemInternet,...,SemInternet,SemInternet,SemInternet,SemInternet,Anual,Nao,CartaoCredito,19.80,457.30,Nao

In [8]:



print(tabela.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5974 entries, 0 to 5985
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   IDCliente               5974 non-null   object
 1   Genero                  5974 non-null   object
 2   Aposentado              5974 non-null   int64
 3   Casado                  5974 non-null   object
 4   Dependentes             5974 non-null   object
 5   MesesComoCliente        5974 non-null   int64
 6   ServicoTelefone         5974 non-null   object
 7   MultiplasLinhas         5974 non-null   object
 8   ServicoInternet         5974 non-null   object
 9   ServicoSegurancaOnline  5974 non-null   object
 10  ServicoBackupOnline     5974 non-null   object
 11  ProtecaoEquipamento     5974 non-null   object
 12  ServicoSuporteTecnico   5974 non-null   object
 13  ServicoStreamingTV      5974 non-null   object
 14  ServicoFilmes           5974 non-null   object
 15  TipoContrato            5974 non-null   object
 16  FaturaDigital           5974 non-null   object
 17  FormaPagamento          5974 non-null   object
 18  ValorMensal             5974 non-null   float64
 19  TotalGasto              5974 non-null   float64
 20  Churn                   5974 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.0+ MB
None

In [6]:
#passo 4: análise inicial
print(tabela["Churn"].value_counts())
print(tabela["Churn"].value_counts(normalize=True).map("{:.2%}".format))

Nao    4387
Sim    1587
Name: Churn, dtype: int64
Nao    73.43%
Sim    26.57%
Name: Churn, dtype: object

In [10]:
# criar gráfico
import plotly.express as px
for coluna in tabela.columns:
    grafico = px.histogram(tabela, x=coluna, color= "Churn", text_auto=True)
    #exibir grafico
    grafico.show()

NameError: name 'coluna' is not defined